server:
  port: 8085  
    
spring:
  main:
    banner-mode: off
  output:
    ansi:
      enabled: ALWAYS
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER


management:
  endpoint:
    health:      enabled: true
 

